# Docker Compose para desenvolvimento e produção local
version: '3.8'

services:
  app:
    build: .
    container_name: traffic-ops
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - traffic-ops-network

networks:
  traffic-ops-network:
    driver: bridge
